apiVersion: v1
kind: Service
metadata:
  name: model-serving
spec:
  type: NodePort
  selector:
    app: model-serving
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
