name: Test and Build Image

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build training image and run unit test
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/train/Dockerfile
          push: false
          target: test
          tags: train:test

      - name: Build serving image and run unit test
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/serving/Dockerfile
          push: false
          target: test
          tags: serving:test
